### PR TITLE
Handle Query String and allow some redirects

### PR DESCRIPTION
**Pull request by devotox**
* We handle the possibility of there being a query string along with the path
* We allow redirects as long as the redirect is not going to a path ending in a slash or without a slash (for strip-slash)

### CODE REVIEW

**Review by devotox — COMMENTED** [review]
Sorry my file editor changed all quotes as well

**Comment by devotox** [comment]
cc: @ascorbic

**Comment by devotox** [comment]
@ascorbic updated

**Review by ascorbic — APPROVED** [review]
This is great. Thanks!

**Pull request merged**
